version: '3.8'

services:
  us_nordvpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - TOKEN=e9f2ab1346dd235938e478812fee2d88bcd29b2a60ea56194c7eb6e9180a13ed
      - CONNECT=United_States  # Explicitly connect to a US server
      - NETWORK=192.168.1.0/24
      - NORDVPN_COUNTRY=United_States  # Explicitly set the country
      - NORDVPN_CATEGORY=standard  # Optional, specify category if needed
    ports:
      - "8001:8001"    # Expose the HTTP port
      - "443:443"  # Expose the HTTPS port if needed
    devices:
      - /dev/net/tun
    restart: always
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile-us
    volumes:
      - ./nginx-us.conf:/etc/nginx/nginx.conf  # Correct path to nginx.conf
      - ./certs:/etc/nginx/certs           # Mount certificates directory for NGINX
    depends_on:
      - us_nordvpn
    restart: always
    network_mode: service:us_nordvpn  # Share network with nordvpn service

  nordvpn-italy:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - TOKEN=e9f2ab1346dd235938e478812fee2d88bcd29b2a60ea56194c7eb6e9180a13ed
      - CONNECT=Italy  # Explicitly connect to a US server
      - NETWORK=192.168.1.0/24
      - NORDVPN_COUNTRY=Italy  # Explicitly set the country
      - NORDVPN_CATEGORY=standard  # Optional, specify category if needed
    ports:
      - "8002:8002"    # Expose the HTTP port
      - "446:446"  # Expose the HTTPS port if needed
    devices:
      - /dev/net/tun
    restart: always
  reverse-proxy-v2:
    build:
      context: .
      dockerfile: Dockerfile-italy
    volumes:
      - ./nginx-italy.conf:/etc/nginx/nginx.conf  # Correct path to nginx.conf
      - ./certs:/etc/nginx/certs           # Mount certificates directory for NGINX
    depends_on:
      - nordvpn-italy
    restart: always
    network_mode: service:nordvpn-italy  # Share network with nordvpn service
    