FROM nginx:1.21.1-alpine

# Remove default NGINX configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom NGINX configuration file
COPY nginx-canada.conf /etc/nginx/nginx.conf

# Copy SSL certificates
# COPY certs/ca-certificates.crt /etc/nginx/certs/ca-certificates.crt
# HEALTHCHECK --interval=5s --timeout=2s CMD curl --fail http://localhost || kill 1

EXPOSE 8005
# EXPOSE 445

ENTRYPOINT ["nginx", "-g", "daemon off;"]